import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../globals.css'
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import AuthProvider from "@/redux/provider/authProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <section>
            <AuthProvider>
                <Navbar />
                {children}
                <Footer />
            </AuthProvider>

        </section>
        </body>
        </html>
    );
}
